baseUrl = "https://blog.peterchai.co.uk"
languageCode = "en-us"
theme = "hugo-theme-hello-friend"
paginate = 5
enableEmoji = true

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "content/posts"
  # "light" or "dark"
  defaultTheme = "dark"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2
  # Enable to show reading time in minutes for posts
  showReadingTime = true

[languages]
  [languages.en]
    title = "Pete's Blog"
    subtitle = "Yet another programmer's blog"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"
    lastModDisplay = "Modified:"

    [languages.en.params.logo]
      logoText = "pete@myblog:~$"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "home"
        name = "Home"
        url = "/"
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "archive"
        name = "Archive"
        url = "/archive"
